version: "3.7"
services:
    mysql:
        image: mysql:latest
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: travel
            MYSQL_ROOT_PASSWORD: travel9012
        ports:
            - 8742:3306
        container_name: travel_mysql

    api:
        build:
            context: .
            dockerfile: Docker/api/Dockerfile
        restart: always
        container_name: travel_api
        depends_on:
            - mysql
        volumes:
            - .:/var/www/api

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/api
            - ./Docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 9999:80
        depends_on:
            - api
        container_name: travel_nginx

